### ISSUE TITLE
Release Python bindings to PyPI

### ISSUE THREAD

**Issue by althonos** [ksahlin/strobealign#496]
Hi! I was about to have a look at making bindings for `strobealign` but I see you made some already 😃 Would you consider releasing the library to PyPI? It would make it much easier to integrate with other Python projects.

So far I can get the project to build with `cibuildwheel` with minimal changes to `pyproject.toml` so making wheels would be quite easy as well, and you could do that in CI to release them on tagged commits (I have an example here for a large matrix of Python versions and platforms: https://github.com/althonos/pyjess/blob/main/.github/workflows/package.yml, but in essence you just need the [`pypa/cibuildwheel`](https://github.com/pypa/cibuildwheel) action). 

The updated `pyproject.toml`:
<details>

```toml
[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build>=0.13",
    "cmake>=3.18",
    "ninja; platform_system!='Windows'",
    "nanobind>=0.2.0",
]

[project]
name = "strobealign"
version = "0.16.0"
license = "MIT"
requires-python = ">=3.10"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.cibuildwheel.linux]
before-all = "yum install -y isa-l-devel"
```

</details>

I would also suggest switching to `scikit-build-core` instead of `scikit-build` for better forward compatibility, this would also avoid to manually require `cmake` and `ninja` as `scikit-build-core` handles the build dependencies a bit better (see https://scikit-build-core.readthedocs.io/). Also happy to help / PR for that 👍
